import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { MyContextProvider } from './components/myContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sefer Bul',
  description: 'Generated by umut Akkıran',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-[#fcfcfc] via-white to-green-200 ">
        <MyContextProvider>
         {children}
        </MyContextProvider> 
        </body>
    </html>
  )
}
